### ISSUE TITLE
What is the purpose of the package?

### ISSUE THREAD

**Issue by kpym** [go-latex/latex#37]
Is it supposed to be a MathJax version for Go ? Or more like the go tools (`gofmt`,...) but for latex ? Is it supposed one day to become a complete tex implementation in go ?

**Comment by sbinet** [comment]
hi,

> Is it supposed to be a MathJax version for Go ?

yes. (eventually)

> Or more like the go tools (gofmt,...) but for latex ? 

yes, that as well. (eventually)

> Is it supposed one day to become a complete tex implementation in go ?

also yes. (eventually)

actually, a complete TeX implementation (TeX, not (yet) LaTeX) in Go is already available there:

- https://star-tex.org/x/tex
- https://star-tex.org/x/tex/internal/xtex
- https://star-tex.org/x/tex/cmd/star-tex


`star-tex` is the new place where all the `go-latex` goals are supposed to be met.
`star-tex` is the automatic translation of `tex.web` into Pascal and then into Go (under `star-tex.org/x/internal/xtex`)

what is missing in `star-tex` is:

- providing a pure-Go implementation of `type1` and `pk` fonts
- providing a pure-Go `dvitopdf` implementation
- providing a pure-Go `dvitopng` implementation
- providing a pure-Go set of builtin macros for LaTeX support

then split out the `internal/xtex` package into manageable, reusable and focused packages (`dvi`, `matheq`, ...)

**Comment by kpym** [comment]
@sbinet very very interesting ! Have you write somewhere a blog post or a documentation that describe the project and how you have achieved the transpilation from pascal to go ? 

As this is an automatic transpilation I suppose that the go version does not benefit from the power of parallel programming (goroutines)  ?

**Comment by sbinet** [comment]
the tool that was used to apply the automatic conversion was written by cznic:
- https://gitlab.com/cznic/web2go

I asked him whether he was considering writing a little blurb or blog post about it but he declined :)
(I was also rather interested in his strategy and the pitfalls he may have faced)

> As this is an automatic transpilation I suppose that the go version does not benefit from the power of parallel programming (goroutines) ?

indeed, it's a rather blunt transpilation with no concurrency in the mix.
that's why I'd like to be able to split it up into multiple (more manageable) packages.

as soon as I (but I am fine other people sending patches :P) finish the DVI->PDF or DVI->PNG support (this means adding support for either `pk` or `type1` fonts), I'll cut `v0.3.0` and make an announcement.
I must admit I've lost a bit of steam.
but the action is happening there:
- https://git.sr.ht/~sbinet/star-tex/tree/dvi (`dvi` branch)
- https://git.sr.ht/~sbinet/star-tex/tree/type1-font (`type1` branch)
- https://git.sr.ht/~sbinet/star-tex/tree/font-pk (`font-pk` branch)

**Comment by kpym** [comment]
> the tool that was used to apply the automatic conversion was written by cznic:
> 
> * https://gitlab.com/cznic/web2go

Thanks for this link. I was not aware about this project.


> I asked him whether he was considering writing a little blurb or blog post about it but he declined :)
> (I was also rather interested in his strategy and the pitfalls he may have faced)

What a pity he didn't want to write something about it. I'll try to ask him too. Maybe he'll end up doing it ;)

 
> > As this is an automatic transpilation I suppose that the go version does not benefit from the power of parallel programming (goroutines) ?
> 
> indeed, it's a rather blunt transpilation with no concurrency in the mix.
> that's why I'd like to be able to split it up into multiple (more manageable) packages.

This will be fantastic.

 
> as soon as I (but I am fine other people sending patches :P) finish the DVI->PDF or DVI->PNG support (this means adding support for either `pk` or `type1` fonts), I'll cut `v0.3.0` and make an announcement.

Are you sure that you want to do this directly ? May be DVI(X) → [Canvas](https://github.com/tdewolff/canvas) ?
This is something that probably I would like to work on.


> I must admit I've lost a bit of steam.
> but the action is happening there:
> 
> * https://git.sr.ht/~sbinet/star-tex/tree/dvi (`dvi` branch)
> * https://git.sr.ht/~sbinet/star-tex/tree/type1-font (`type1` branch)
> * https://git.sr.ht/~sbinet/star-tex/tree/font-pk (`font-pk` branch)

Are you sure you want to work with `type1` fonts and not with `TTF` and `OTF`?
I know this means switching from `tex` to something like `xetex`, but maybe that's the way to go... the poor UTF support in `tex` is really annoying.  

Do you know `tectonic` project ? (He is ambitioning to port `xetex` to Rust.)

**Comment by sbinet** [comment]
> Are you sure that you want to do this directly ? May be DVI(X) → Canvas ?

the `dvi` branch is trying to put in place the necessary scaffolding to be able to read/decode a DVI file (mostly done) and then produce something (PDF, PNG) (that's what needs to be done).
the most difficult thing being loading the correct fonts (right now, only `type1` and `pk` fonts are supported by `tex.web` and thus `star-tex`).

the plan is to be able to produce a `.pdf` document from a (plain) `.tex` document, with `star-tex.org/x/tex` (in pure-Go) + an already installed TeX distribution system.

> Are you sure you want to work with type1 fonts and not with TTF and OTF?

my strategy was to be able to replicate `tex.web`, first.
as it was the most minimal working TeX system, I thought it would be easier to do.
handling TTF/OTF meant to be able to create new code w/o much documentation (or w/o looking at GPL-ed code).
it seemed easier to first get a handle on the TeX system at large first and then improve on it. (I have been a *user* of LaTeX for >20yrs, but never went behind the curtain before then)

I now of the tectonic project.
and other projects:
- https://github.com/tex-other

(my favorite one being https://github.com/xymostech/XymosTeX)

**Comment by kpym** [comment]
> > Are you sure that you want to do this directly ? May be DVI(X) → Canvas ?
> 
> the `dvi` branch is trying to put in place the necessary scaffolding to be able to read/decode a DVI file (mostly done) and then produce something (PDF, PNG) (that's what needs to be done).

I can't find the `dvi` branch. I see only a `main` branch in `https://git.sr.ht/~sbinet/star-tex`.
Are you following some `dvi` specifications ? If yes, where can I find them ? 


> the most difficult thing being loading the correct fonts (right now, only `type1` and `pk` fonts are supported by `tex.web` and thus `star-tex`).
> the plan is to be able to produce a `.pdf` document from a (plain) `.tex` document, with `star-tex.org/x/tex` (in pure-Go) + an already installed TeX distribution system.

Stupid question : is it not possible for the `dvi` renderer part to use converted `otf` fonts in place of the original `type1` ? If this is possible, may be a first step will be to work with "adjusted" tex distribution, where the `type1` fonts are doubled by converted `otf` fonts, because there are available go libraries for this type of fonts.


> > Are you sure you want to work with type1 fonts and not with TTF and OTF?
> 
> my strategy was to be able to replicate `tex.web`, first.
> as it was the most minimal working TeX system, I thought it would be easier to do.

This seems reasonable. The only problem is that there are no (as far as I know) a go library for `type1` fonts :(


> handling TTF/OTF meant to be able to create new code w/o much documentation (or w/o looking at GPL-ed code).
> it seemed easier to first get a handle on the TeX system at large first and then improve on it. (I have been a _user_ of LaTeX for >20yrs, but never went behind the curtain before then)

Me too ;)

**Comment by sbinet** [comment]
the `dvi` branch is there:
- https://git.sr.ht/~sbinet/star-tex/tree/dvi

I've put some references for `dvi` on the tracker:
- https://todo.sr.ht/~sbinet/star-tex/3

same for `dvi2pdf`, `dvi2png` and `type1`/`pk`:
- https://todo.sr.ht/~sbinet/star-tex/5
- https://todo.sr.ht/~sbinet/star-tex/4
- https://todo.sr.ht/~sbinet/star-tex/8
- https://todo.sr.ht/~sbinet/star-tex/11

> is it not possible for the dvi renderer part to use converted otf fonts in place of the original type1 

I don't know of a tool that would do what you are describing.
`type1` fonts are indeed complicated (you need a PostScript interpreter for one thing).
I think it will be more tractable to focus on the `pk` fonts. (the `pk`-related branch seems to be able to correctly decode those, now what still needs to be done is to present the data as a `golang.org/x/image/font.Face` (or something else?) so as to be able to actually render the text)

could we migrate this discussion over to `star-tex` list?
- https://lists.sr.ht/~sbinet/star-tex
- `mailto:~sbinet/star-tex@lists.sr.ht`

**Comment by kpym** [comment]
> could we migrate this discussion over to the `star-tex` list?
> 
> * https://lists.sr.ht/~sbinet/star-tex
> * `mailto:~sbinet/star-tex@lists.sr.ht`

We can try, I have never used `sr.ht` before. I just created a free account there.

**Comment by tommyo** [comment]
My first thought when I found this project was how thorough and awesome it looked, if only there was any documentation about how to use it, or at least what it's intentions were. Luckily I decided to dig deeper and found this "issue", because your first answer filled in a huge number of gaps. You should move a bunch of that into the `README.md`.

**Comment by sbinet** [comment]
You are not wrong.
I'll try to send a PR when in front of a real keyboard.

**Comment by sbinet** [comment]
(closing, feel free to reopen if you feel it hasn't been properly addressed.)
