### ISSUE TITLE
Unknown ast node *ast.Sup / *ast.Sub

### ISSUE THREAD

**Issue by brrm** [go-latex/latex#40]
Hi,
When trying to render an expression with a subscript or superscipt such as `$x^n$` using the example code in the README (I've only changed the expression, nothing else) I get the error `unknown ast node *ast.Sup` (or `unknown ast node *ast.Sub` if using a subscript).

**Comment by sbinet** [comment]
Yeah, superscripts aren't supported (neither are subscripts).
It's filed as https://github.com/go-latex/latex/issues/17

(This is kind of the reason for starting the work on star-tex.org/x/tex).
