### ISSUE TITLE
Operators [^] are not supported

### ISSUE THREAD

**Issue by Lyndon1994** [go-latex/latex#41]
`(\sqrt[2]{3})^{9}!`
`x^n + y^n = z^n`

Unable to convert

```go
package main

import (
	"os"

	"github.com/go-latex/latex/drawtex/drawimg"
	"github.com/go-latex/latex/mtex"
)

func main() {
	f, err := os.Create("output.png")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	dst := drawimg.NewRenderer(f)
	err = mtex.Render(dst, `$ x^n + y^n = z^n $`, 12, 72, nil)
	if err != nil {
		panic(err)
	}

	err = f.Close()
	if err != nil {
		panic(err)
	}
}
```
output:
`
panic: unknown ast node *ast.Sup

goroutine 1 [running]:
github.com/go-latex/latex/mtex.(*visitor).Visit(0xc000174000, 0x11a9678, 0xc00000c138, 0x11a8748, 0xc000174000)
        /Users/linyi05/go/pkg/mod/github.com/go-latex/latex@v0.0.0-20210823091927-c0d11ff05a81/mtex/parser.go:128 +0xec8
github.com/go-latex/latex/mtex.(*visitor).Visit(0xc000174000, 0x11a95e8, 0xc000022080, 0x203000, 0x13a0428)
        /Users/linyi05/go/pkg/mod/github.com/go-latex/latex@v0.0.0-20210823091927-c0d11ff05a81/mtex/parser.go:106 +0x489
github.com/go-latex/latex/ast.Walk(0x11a8748, 0xc000174000, 0x11a95e8, 0xc000022080)
        /Users/linyi05/go/pkg/mod/github.com/go-latex/latex@v0.0.0-20210823091927-c0d11ff05a81/ast/walk.go:22 +0x55
github.com/go-latex/latex/ast.Walk(0x11a8748, 0xc000174000, 0x11a9978, 0xc00000c228)
        /Users/linyi05/go/pkg/mod/github.com/go-latex/latex@v0.0.0-20210823091927-c0d11ff05a81/ast/walk.go:29 +0x168
github.com/go-latex/latex/mtex.(*parser).parse(0xc00006e660, 0x117e2a5, 0x13, 0x4028000000000000, 0x4052000000000000, 0xc000117e00, 0xb42f9178e3e3fe15, 0x18, 0x115fee0)
        /Users/linyi05/go/pkg/mod/github.com/go-latex/latex@v0.0.0-20210823091927-c0d11ff05a81/mtex/parser.go:59 +0x3c5
github.com/go-latex/latex/mtex.Parse(0x117e2a5, 0x13, 0x4028000000000000, 0x4052000000000000, 0x11a9d88, 0xc00000c0c0, 0x0, 0xc000117ed0, 0x100d0bb, 0xc000010750)
        /Users/linyi05/go/pkg/mod/github.com/go-latex/latex@v0.0.0-20210823091927-c0d11ff05a81/mtex/parser.go:25 +0xc6
github.com/go-latex/latex/mtex.Render(0x11a8728, 0xc000010750, 0x117e2a5, 0x13, 0x4028000000000000, 0x4052000000000000, 0x0, 0xc000064058, 0x1019001)
        /Users/linyi05/go/pkg/mod/github.com/go-latex/latex@v0.0.0-20210823091927-c0d11ff05a81/mtex/render.go:32 +0x32e
main.main()
        /Users/linyi05/go/src/study/latex/main.go:18 +0x125
`

**Comment by sbinet** [comment]
thanks for the report (and trying to use `go-latex/latex`).

it's a known issue: https://github.com/go-latex/latex/issues/17
