### ISSUE TITLE
dependency on github.com/go-fonts/dejavu v0.3.2, which doesn't exist (anymore?)

### ISSUE THREAD

**Issue by fzipp** [go-latex/latex#46]
The go.mod file lists v0.3.2 of `github.com/go-fonts/dejavu` as a dependency:
https://github.com/go-latex/latex/blob/5c1ce85aa4ea1636d7a06434177ed7ef995a1064/go.mod#L7

However, the latest version tag of go-fonts/dejavu is v0.2.1: https://github.com/go-fonts/dejavu/tags

There seems to have been a v0.3.2 at one point: https://pkg.go.dev/github.com/go-fonts/dejavu?tab=versions

**Comment by sbinet** [comment]
I've published all missing tags.
thanks for the issue.
